M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date do 04 jul 2024 08:26:30
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-04T08:26:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X2.5984Y-2.3189
X2.5984Y-2.4921
T0
M30
