M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-01-28T20:04:08+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-28T20:04:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X67.305Y-57.11
X67.305Y-62.89
M30
